Create examples detailing how to use custom callbacks, synthesizers, and models with PrivacyRaven's attack suite
trailofbits/PrivacyRaven pull request #57
Opened 2021-01-01 04:15 UTC by pwang00

Addresses #47

2021-01-01 04:22 UTC, suhacker1 requested changes
Change "Pytorch Lightning bolt" to "[PyTorch Lightning Bolts](https://pytorch-lightning-bolts.readthedocs.io/en/latest/)". 
 
Immediately linking to the documentation makes it easier for the user to understand the code and eventually implement their own version.

2021-01-04 21:26 UTC, suhacker1 commented
I'm a little confused as to what the create_model.py file is for since you're not actually creating a new model there. For model creation, I was assuming a new model would be created and then either attacked or used as the substitute model architecture

2021-01-04 22:19 UTC, pwang00 commented
I believe all changes have been accounted for.  I removed create_model.py since it doesn't seem to do what its filename suggests, but will consider creating a working example and submit it in a future PR.

2021-01-06 00:34 UTC, pwang00 commented on examples/create_synthesizer.py
> +model = train_mnist_victim(gpus=1)
Will do.  Should we also consider make this explicit in PrivacyRaven's README?

2021-01-06 10:12 UTC, suhacker1 commented on examples/create_synthesizer.py
> +model = train_mnist_victim(gpus=1)
I think it's okay for now- we don't want to overload the information in the README either

2021-01-06 10:14 UTC, suhacker1 approved these changes

2021-01-06 18:33 UTC, merged